version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
